openapi: 3.0.4
info:
  title: Go Task App
servers:
  - url: https://localhost:4000
tags:
  - name: task
  - name: user
paths:
  /task/{taskId}:
    put:
      tags:
        - task
      summary: タスクの更新
      operationId: updateTask
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
        required: true
      responses:
        '200':
          description: 成功
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: 入力値が不正
        '401':
          description: 認証エラー
        '403':
          description: 権限エラー
        default:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
    delete:
      tags:
        - task
      summary: タスクの削除
      operationId: deleteTask
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 成功
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: 入力値が不正
        '401':
          description: 認証エラー
        '403':
          description: 権限エラー
        default:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
  /task:
    post:
      tags:
        - task
      summary: タスクの作成
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
        required: true
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  task:
                    $ref: "#/components/schemas/Task"
        '400':
          description: 入力値が不正
        '401':
          description: 認証エラー
        '403':
          description: 権限エラー
        default:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
  /tasks:
    get:
      tags:
        - task
      summary: タスクの取得
      operationId: getTask 
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: "#/components/schemas/Task"
        '400':
          description: 入力値が不正
        '401':
          description: 認証エラー
        '403':
          description: 権限エラー
        default:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
  /sign-in:
    post:
      tags:
        - user
      summary: サインイン
      operationId: singIn
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  task:
                    $ref: "#/components/schemas/User"
        '400':
          description: 入力値が不正
        default:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /sign-up:
    post:
      tags:
        - user
      summary: サインアップ
      operationId: singUp
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  task:
                    $ref: "#/components/schemas/User"
        '400':
          description: 入力値が不正
        default:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: タスク1
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        userId:
          type: integer
          format: int64
          example: 1
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: satoru-gojo
        createdAt:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        error:
          type: string
          example: 入力値が不正です。
