CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tasks
ADD COLUMN user_id INT,
ADD CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES users(id);
